replicaCount: 3

image:
  repository: adimane0801/devops-app
  tag: v2
  pullPolicy: Always

service:
  type: NodePort
  port: 80

resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi